# Generated by Django 3.2.9 on 2021-12-27 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='orderstatus_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderstatus_order', to='Restaurant.orderstatus'),
        ),
        migrations.AddField(
            model_name='menu',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.branch'),
        ),
        migrations.AddField(
            model_name='menu',
            name='food_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_menu', to='Restaurant.food'),
        ),
        migrations.AddField(
            model_name='food',
            name='meal_category',
            field=models.ManyToManyField(related_name='mealcategory_food', to='Restaurant.MealCategory'),
        ),
        migrations.AddField(
            model_name='food',
            name='type_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typecategory_food', to='Restaurant.typecategory'),
        ),
        migrations.AddField(
            model_name='branch',
            name='manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.manager'),
        ),
        migrations.AddField(
            model_name='branch',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_branch', to='Restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='branch',
            name='type_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.typecategory'),
        ),
        migrations.AddField(
            model_name='address',
            name='customer_id',
            field=models.ManyToManyField(related_name='customer_address', to='accounts.Customer'),
        ),
    ]
