# Generated by Django 3.2.9 on 2022-01-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
