# Generated by Django 3.2.9 on 2022-01-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_auto_20211228_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('orderd', 'Ordered'), ('paid', 'Paid'), ('sent', 'Sent'), ('delivered', 'Delivered')], default='ordered', max_length=50),
        ),
    ]
