# Generated by Django 3.2.9 on 2022-01-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0005_auto_20220106_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('paid', 'Paid'), ('sent', 'Sent'), ('delivered', 'Delivered')], default='ordered', max_length=50),
        ),
    ]
